# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Mehmet_DELIOGLU\Desktop\Python dersleri\Deneme\btk_tensorflow\btk_m\PyQt5\checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 407)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSecilenAlHobiler = QtWidgets.QPushButton(self.centralwidget)
        self.btnSecilenAlHobiler.setGeometry(QtCore.QRect(50, 210, 75, 23))
        self.btnSecilenAlHobiler.setObjectName("btnSecilenAlHobiler")
        self.lblResultHobiler = QtWidgets.QLabel(self.centralwidget)
        self.lblResultHobiler.setGeometry(QtCore.QRect(20, 250, 161, 91))
        self.lblResultHobiler.setText("")
        self.lblResultHobiler.setObjectName("lblResultHobiler")
        self.grupHobiler = QtWidgets.QGroupBox(self.centralwidget)
        self.grupHobiler.setGeometry(QtCore.QRect(20, 20, 161, 181))
        self.grupHobiler.setObjectName("grupHobiler")
        self.widget = QtWidgets.QWidget(self.grupHobiler)
        self.widget.setGeometry(QtCore.QRect(30, 40, 111, 111))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbSinema = QtWidgets.QCheckBox(self.widget)
        self.cbSinema.setObjectName("cbSinema")
        self.verticalLayout.addWidget(self.cbSinema)
        self.cbKitap = QtWidgets.QCheckBox(self.widget)
        self.cbKitap.setObjectName("cbKitap")
        self.verticalLayout.addWidget(self.cbKitap)
        self.cbSpor = QtWidgets.QCheckBox(self.widget)
        self.cbSpor.setObjectName("cbSpor")
        self.verticalLayout.addWidget(self.cbSpor)
        self.grupDersler = QtWidgets.QGroupBox(self.centralwidget)
        self.grupDersler.setGeometry(QtCore.QRect(210, 20, 161, 181))
        self.grupDersler.setObjectName("grupDersler")
        self.layoutWidget = QtWidgets.QWidget(self.grupDersler)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 111, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbTasarm = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbTasarm.setObjectName("cbTasarm")
        self.verticalLayout_2.addWidget(self.cbTasarm)
        self.cbProgramlama = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbProgramlama.setObjectName("cbProgramlama")
        self.verticalLayout_2.addWidget(self.cbProgramlama)
        self.cbMatematik = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbMatematik.setObjectName("cbMatematik")
        self.verticalLayout_2.addWidget(self.cbMatematik)
        self.btnSecilenAlDersler = QtWidgets.QPushButton(self.centralwidget)
        self.btnSecilenAlDersler.setGeometry(QtCore.QRect(240, 210, 75, 23))
        self.btnSecilenAlDersler.setObjectName("btnSecilenAlDersler")
        self.lblResultDersler = QtWidgets.QLabel(self.centralwidget)
        self.lblResultDersler.setGeometry(QtCore.QRect(210, 250, 161, 91))
        self.lblResultDersler.setText("")
        self.lblResultDersler.setObjectName("lblResultDersler")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSecilenAlHobiler.setText(_translate("MainWindow", "Seçilenleri Al"))
        self.grupHobiler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbSinema.setText(_translate("MainWindow", "Sinema"))
        self.cbKitap.setText(_translate("MainWindow", "Kitap"))
        self.cbSpor.setText(_translate("MainWindow", "Spor"))
        self.grupDersler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbTasarm.setText(_translate("MainWindow", "Tasarım"))
        self.cbProgramlama.setText(_translate("MainWindow", "Programlama"))
        self.cbMatematik.setText(_translate("MainWindow", "Matematik"))
        self.btnSecilenAlDersler.setText(_translate("MainWindow", "Seçilenleri Al"))
