# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI_MainWindow(object):
    def setupUi(self, UI_MainWindow):
        UI_MainWindow.setObjectName("UI_MainWindow")
        UI_MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(UI_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 47, 13))
        self.label_2.setObjectName("label_2")
        self.txt_sayi1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_sayi1.setGeometry(QtCore.QRect(80, 40, 151, 31))
        self.txt_sayi1.setObjectName("txt_sayi1")
        self.txt_sayi2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_sayi2.setGeometry(QtCore.QRect(80, 90, 151, 31))
        self.txt_sayi2.setObjectName("txt_sayi2")
        self.btn_toplama = QtWidgets.QPushButton(self.centralwidget)
        self.btn_toplama.setGeometry(QtCore.QRect(80, 140, 75, 31))
        self.btn_toplama.setObjectName("btn_toplama")
        self.btn_carpma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_carpma.setGeometry(QtCore.QRect(260, 140, 75, 31))
        self.btn_carpma.setObjectName("btn_carpma")
        self.btn_bol = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bol.setGeometry(QtCore.QRect(350, 140, 81, 31))
        self.btn_bol.setObjectName("btn_bol")
        self.btn_cikarma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikarma.setGeometry(QtCore.QRect(170, 140, 81, 31))
        self.btn_cikarma.setObjectName("btn_cikarma")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 200, 141, 21))
        self.label_3.setObjectName("label_3")
        UI_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UI_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        UI_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UI_MainWindow)
        self.statusbar.setObjectName("statusbar")
        UI_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UI_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(UI_MainWindow)

    def retranslateUi(self, UI_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        UI_MainWindow.setWindowTitle(_translate("UI_MainWindow", "MainWindow"))
        self.label.setText(_translate("UI_MainWindow", "Sayı1: "))
        self.label_2.setText(_translate("UI_MainWindow", "Sayı 2: "))
        self.btn_toplama.setText(_translate("UI_MainWindow", "Toplam"))
        self.btn_carpma.setText(_translate("UI_MainWindow", "Çarpma"))
        self.btn_bol.setText(_translate("UI_MainWindow", "Bölme"))
        self.btn_cikarma.setText(_translate("UI_MainWindow", "Çıkarma"))
        self.label_3.setText(_translate("UI_MainWindow", "Sonuç: "))
