# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comboBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 438)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cbSehirler = QtWidgets.QComboBox(self.centralwidget)
        self.cbSehirler.setGeometry(QtCore.QRect(40, 40, 221, 51))
        self.cbSehirler.setObjectName("cbSehirler")
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(280, 40, 221, 51))
        self.lblResult.setText("")
        self.lblResult.setObjectName("lblResult")
        self.GetItem = QtWidgets.QPushButton(self.centralwidget)
        self.GetItem.setGeometry(QtCore.QRect(40, 120, 221, 41))
        self.GetItem.setObjectName("GetItem")
        self.LoadItems = QtWidgets.QPushButton(self.centralwidget)
        self.LoadItems.setGeometry(QtCore.QRect(280, 120, 221, 41))
        self.LoadItems.setObjectName("LoadItems")
        self.ClearItem = QtWidgets.QPushButton(self.centralwidget)
        self.ClearItem.setGeometry(QtCore.QRect(40, 180, 221, 41))
        self.ClearItem.setObjectName("ClearItem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 535, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GetItem.setText(_translate("MainWindow", "Get Item"))
        self.LoadItems.setText(_translate("MainWindow", "Load Item"))
        self.ClearItem.setText(_translate("MainWindow", "Clear Item"))
